services:
  - type: web
    name: inventory-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: SHEET_ID
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_KEY
        sync: false
